---
- apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - alpine-sdk
    - procps
    - openjdk8
    - autoconf
    - ncurses
    - automake
    - libtool
    - fts-dev
    - curl-dev
    - apr-dev
    - cyrus-sasl-dev
    - unzip
    - tar
    - gzip
    - bzip2
    - bash
- file:
    state: directory
    dest: /opt
- unarchive:
    src: http://apache.claz.org/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
    copy: no
    dest: /opt
    creates: no
- name: Move Spark directory to /opt/spark 
  shell: mv -v /opt/spark-2.3.1-bin-hadoop2.7 /opt/spark
- lineinfile:
    line: 'export PATH=$PATH:/opt/spark/bin:/opt/spark/sbin'
    dest: /etc/profile
...
