---
- name: Install Spark dependencies.
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - alpine-sdk
    - procps
    - openjdk8
    - autoconf
    - ncurses
    - automake
    - libtool
    - fts-dev
    - curl-dev
    - apr-dev
    - cyrus-sasl-dev
    - unzip
    - tar
    - gzip
    - bzip2
    - bash
- name: Copy the relevant rc files to /root.
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items:
    - src: vimrc
      dest: /root/.vimrc
    - src: bashrc
      dest: /root/.bashrc
    - src: wakatime.cfg
      dest: /root/.wakatime.cfg
    - src: git-completion.bash
      dest: /root/.git-completion.bash
- name: Create the /opt directory.
  file:
    state: directory
    dest: /opt
- name: Download and untar the spark binary. 
  unarchive:
    src: http://apache.claz.org/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
    copy: no
    dest: /opt
    creates: no
- name: Remove spark directory if it exists for some reason.
  file:
    dest: /opt/spark
    state: absent
- name: Move Spark directory to /opt/spark 
  shell: mv -v /opt/spark-2.3.1-bin-hadoop2.7 /opt/spark
- name: Make sure the relevant directories are added to the path. 
  lineinfile:
    line: 'export PATH=$PATH:/opt/spark/bin:/opt/spark/sbin'
    dest: /etc/profile
...
